project:
  type: website
  output-dir: docs

website:
  title: "Francesco Neri"
  search: false
  cookie-consent:
    type: express
    style: simple
    palette: light
  google-analytics:
    tracking-id: "G-Y23TGWHRGM"
    anonymize-ip: true
  navbar:
    left:
      - href: index.qmd
        text: About Me
      - href: resume.qmd
        text: Resume
      - href: projects.qmd
        text: My Academic Projects

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true

editor: visual
